### ISSUE TITLE
SDK封装建议原样返回API实际返回内容

### ISSUE THREAD

**Issue by isayme** [teambition/tws-auth#1]
如果返回的数据经过SDK内部处理, 使用者还需要翻代码才知道到底处理了什么.

不过, 有文档说清楚SDK做了那部分的抽象处理也是可以的.

**Comment by DavidCai1993** [comment]
Resolved in: https://github.com/teambition/tws-auth/commit/d91c95fc34de0d887fd4d164a49a45265a8642e1
