### ISSUE TITLE
超时 3s 后会重试, 在底层 api 不保证幂等的情况下很危险

### ISSUE THREAD

**Issue by JhinDeng** [teambition/tws-auth#15]
原因是由下面两行代码导致的
https://github.com/teambition/tws-auth/blob/master/src/client.ts/#L12-L13
https://github.com/teambition/tws-auth/blob/master/src/client.ts/#L127

可以考虑删除 ['ESOCKETTIMEDOUT', 'ETIMEDOUT'] 两个错误码

**Comment by zensh** [comment]
👌
